#!/usr/bin/sh
# @author nate zhou
# @since 2025,2026
# river-classic/modes

map="riverctl map"

floating="floating"
wmenu="[w]iki [h]eart [m]ount [u]nmount [b]lue [s]peaker [e]moji"
dunst="clip-w[i]pe [l]supdates d[w] d[c]al ls[m]us"
wlrctl="[hjkl]cursors [,]left [.]right [m]iddle ^[hjkl]arrows"

# float #######################################################################
riverctl declare-mode "$floating"
$map normal ${mod}+Control f enter-mode "$floating"

$map "$floating" ${mod}+Control  f       enter-mode normal
$map "$floating" None            Escape  enter-mode normal
$map "$floating" None            space   enter-mode normal

$map -repeat "$floating" None h move left 50
$map -repeat "$floating" None j move down 50
$map -repeat "$floating" None k move up 50
$map -repeat "$floating" None l move right 50

$map -repeat "$floating" None y resize horizontal -50
$map -repeat "$floating" None u resize vertical 50
$map -repeat "$floating" None i resize vertical -50
$map -repeat "$floating" None o resize horizontal 50

$map "$floating" ${mod}+Shift h snap left
$map "$floating" ${mod}+Shift j snap down
$map "$floating" ${mod}+Shift k snap up
$map "$floating" ${mod}+Shift l snap right


# wmenu ########################################################################
riverctl declare-mode "$wmenu"
$map normal $mod w enter-mode "$wmenu"

$map "$wmenu" $mod w      enter-mode normal
$map "$wmenu" None space  enter-mode normal
$map "$wmenu" None Escape enter-mode normal

$map "$wmenu" None w spawn "riverctl enter-mode normal && ${HOME}/.local/bin/wiki"
$map "$wmenu" None h spawn "riverctl enter-mode normal && ${HOME}/.local/bin/heart"
$map "$wmenu" None b spawn "riverctl enter-mode normal && ${HOME}/.local/bin/blue"
$map "$wmenu" None m spawn "riverctl enter-mode normal && ${HOME}/.local/bin/saddle --mount"
$map "$wmenu" None u spawn "riverctl enter-mode normal && ${HOME}/.local/bin/saddle --unmount"
$map "$wmenu" None p spawn "riverctl enter-mode normal && ${HOME}/.local/bin/picker"
$map "$wmenu" None s spawn "riverctl enter-mode normal && ${HOME}/.local/bin/speaker"
$map "$wmenu" None e spawn "riverctl enter-mode normal && ${HOME}/.local/bin/emoji"


# dunst ########################################################################
riverctl declare-mode "$dunst"
$map normal $mod x enter-mode "$dunst"

$map "$dunst" $mod z enter-mode normal
$map "$dunst" $mod apostrophe enter-mode normal
$map "$dunst" None space enter-mode normal
$map "$dunst" None Escape enter-mode normal

$map "$dunst" None l spawn "riverctl enter-mode normal && ${HOME}/.local/bin/lsupdates"
$map "$dunst" None w spawn "riverctl enter-mode normal && ${HOME}/.local/bin/wttr"
$map "$dunst" None c spawn "riverctl enter-mode normal && ${HOME}/.local/bin/dcal"
# $map "$dunst" None m spawn "riverctl enter-mode normal && ${HOME}/.local/bin/lsmus"
$map "$dunst" None i spawn "riverctl enter-mode normal && ${HOME}/.local/bin/clip --wipe"


# wlrctl #######################################################################
riverctl declare-mode "$wlrctl"
$map normal $mod slash spawn "killall fcitx5 ; riverctl enter-mode \"$wlrctl\""

$map "$wlrctl" $mod slash  spawn "riverctl spawn \"fcitx5 -d\"; riverctl enter-mode normal"
$map "$wlrctl" None space  spawn "riverctl spawn \"fcitx5 -d\"; riverctl enter-mode normal"
$map "$wlrctl" None Escape spawn "riverctl spawn \"fcitx5 -d\"; riverctl enter-mode normal"

$map -repeat "$wlrctl" None  h spawn "wlrctl pointer move -90 0"
$map -repeat "$wlrctl" None  j spawn "wlrctl pointer move 0 90"
$map -repeat "$wlrctl" None  k spawn "wlrctl pointer move 0 -90"
$map -repeat "$wlrctl" None  l spawn "wlrctl pointer move 90 0"
$map -repeat "$wlrctl" Shift h spawn "wlrctl pointer move -15 0"
$map -repeat "$wlrctl" Shift j spawn "wlrctl pointer move 0 15"
$map -repeat "$wlrctl" Shift k spawn "wlrctl pointer move 0 -15"
$map -repeat "$wlrctl" Shift l spawn "wlrctl pointer move 15 0"

$map "$wlrctl" None slash spawn "riverctl enter-mode normal && wlrctl pointer move 9999 9999"

$map -repeat "$wlrctl" Control h spawn "wtype -k Left"
$map -repeat "$wlrctl" Control j spawn "wtype -k Down"
$map -repeat "$wlrctl" Control k spawn "wtype -k Up"
$map -repeat "$wlrctl" Control l spawn "wtype -k Right"

$map -repeat "$wlrctl" None  comma  spawn "wlrctl pointer click left"
$map -repeat "$wlrctl" None  period spawn "wlrctl pointer click right"
$map -repeat "$wlrctl" Shift comma  spawn "wlrctl pointer click left"
$map -repeat "$wlrctl" Shift period spawn "wlrctl pointer click right"

$map -repeat "$wlrctl" None n spawn "wlrctl pointer scroll 30"
$map -repeat "$wlrctl" None p spawn "wlrctl pointer scroll -30"
