# vim:ft=dosini
# foot/foot.ini
# @author nate zhou
# @since 2024, 2025

include=~/.config/foot/bindings.ini
include=~/.config/foot/colors-dark.ini
include=~/.config/foot/colors-light.ini

font=Maple Mono NF CN:size=13

locked-title=yes

[scrollback]
lines=16384

[url]
launch=qutebrowser ${url}
