# mpd/mpd.conf
# @author nate zhou
# @since 2023,2024,2025,2026

include "outputs.conf"

bind_to_address "127.0.0.1"
port "6600"

auto_update "yes"
restore_paused "yes"

music_directory "~/mus"
playlist_directory "~/mus/.playlists"
db_file "~/.cache/mpd/mpd.db"
log_file "~/.cache/mpd/mpd.log"
pid_file "~/.cache/mpd/mpd.pid"
state_file "~/.cache/mpd/mpdstate"
