# mpd/outputs.conf
# @author nate zhou
# @since 2023,2024,2025,2026

audio_output {
    type "pipewire"
    name "PipeWire Sound Server"
}

audio_output {
	type		"httpd"
	name		"HTTP Stream"
	encoder		"vorbis"
	bind_to_address	"0.0.0.0"
	port		"8000"
	bitrate		"128"
	format		"44100:16:2"
	max_clients	"0"
}

audio_output {
    type "fifo"
    name "Visulaizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}
