theme = "horizon-dark"

[editor.indent-guides]
render = true
skip-level = 1

[editor]
mouse = true
rulers = [120]
cursorline = true
bufferline = "always"
color-modes = true
completion-trigger-len = 1
idle-timeout = 0
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NOM"
mode.insert = "INS"
mode.select = "SEL"
